### PR TITLE
Add Try/Catch to Automation Script Solution Template

### PR DESCRIPTION
**Pull request by BlakeSLC**
Example try catch block inserted into template

### CODE REVIEW

**Comment by SkylineThomasCR** [comment]
Missing ScriptTimeoutException and InteractiveUserDetachedException.

Because exceptions are never rethrown, and the catch all is only logged, scripts will always show *Succeeded*:
image
I'm not sure if we always want to treat an exception as a successfull execution.

**Comment by BlakeSLC** [comment]
> Missing ScriptTimeoutException and InteractiveUserDetachedException.
> 
> Because exceptions are never rethrown, and the catch all is only logged, scripts will always show _Succeeded_: image I'm not sure if we always want to treat an exception as a successfull execution.

The reason I didn't add a throw to those is because if the user aborts, then we shouldn't show a popup or add a log that they aborted the script. To me, an abort is a "successful" execution, as we closed the script as expected.

As for ScriptTimeoutException and InteractiveUserDetachedException, I think those should be handled as normal, no? Interactive is really only for an interactive script, which will require a lot more effort anyway.

**Comment by SkylineThomasCR** [comment]
- Maybe you could add the following comments:
```C#
catch (ScriptAbortException)
{
	// catch normal abort exceptions
	// throw; // Uncomment if it should not be treated as a normal exit of the script.
}
```

- The ScriptTimeoutException needs to be caught and thrown again, otherwise `catch(Exception e)` will catch it, resulting in another *Successfull*.

- Shoudn't `catch(Exception e)` use engine.ExitFail() instead of engine.Log()?
I don't think those exceptions should be treated as *Successfull*
```C#
catch (Exception e)
{
	engine.ExitFail("Run|Something went wrong: " + e);
}
```
This results in a clear message to the user:
image
It also results in a clear log message:
```2024/03/19 18:03:19.262|SLAutomation.exe 10.2.2143.9438|21612|6288|CScriptLoader::ExitNow|DBG|-1|[Thomas Cauwelier] (Script Automation script) EXIT: "Run|Something went wrong: System.InvalidOperationException: Bananas are red"```

- If the purpose of the template is to remind people about these exceptions, shouldn't the InteractiveUserDetachedException be added, but maybe with a comment stating that is can be removed in an non-interactive script? If people forget about it, then it will be caught by `catch(Exception e)` resulting in a *Something went wrong* log line, even though this could also be treated as a normal exit by the user.
```C#
catch (InteractiveUserDetachedException e)
{
	// catch a user detaching from the interactive script.
	// only applicable for interactive scripts, can be removed for non-interactive scripts.
}
```

**Comment by BlakeSLC** [comment]
Great suggestions, updated.

**Review by MichielOda — APPROVED** [review]

**Pull request merged**
